package com.dbengine.sql;

public enum TokenType {
    CREATE, DATABASE, TABLE, COLUMN, USE, DROP, SHOW, TABLES, DATABASES,
    ALTER, ADD, RENAME, TO, TRUNCATE, DESCRIBE, DESC,
    INSERT, INTO, VALUES, SELECT, FROM, WHERE, UPDATE, SET, DELETE,
    AND, OR, NOT, NULL,
    PRIMARY, KEY, INT, VARCHAR, BOOLEAN, FLOAT,
    GROUP, BY, ORDER, ASC, DESC_SORT, LIMIT, DISTINCT,
    COUNT, SUM, AVG, MIN, MAX,
    AS, INNER, JOIN, ON,
    BEGIN, TRANSACTION, COMMIT, ROLLBACK,
    IDENTIFIER, INT_LITERAL, STRING_LITERAL, FLOAT_LITERAL, BOOLEAN_LITERAL,
    LPAREN, RPAREN, COMMA, SEMICOLON, STAR, DOT,
    EQUALS, NOT_EQUALS, LT, GT, LTE, GTE,
    EOF
}
